[package]
name = "behave"
version = "0.1.0"
edition = "2021"

[dependencies]
lazy_static = "1.4.0"
gltf = { git = "https://github.com/Synaptic-Simulations/gltf", features = ["extras", "names"] }
uuid = { version = "0.8", features = ["v4"] }
