[package]
name = "behave-cli"
version = "0.1.0-veryalpha"
edition = "2021"

[[bin]]
name = "behavec"
path = "src/main.rs"

[dependencies]
behave = { path = "../behave" }
clap = "3.0.0-beta.4"
codespan-reporting = "0.11.1"
